# 
# this is a makefile
# 

# default is to make first target
all: helloc hellocpp

helloc: hello_world.c
	gcc -o helloc.lex hello_world.c

hellocpp: hello_world.cpp
	g++ -o hellocpp.lex hello_world.cpp

clean: 
	rm helloc hellocpp

